---
language: ruby
before_install:
  - gem install bundler
install: bundle install
script: bundle exec rake test
notifications:
  email: true
rvm:
  - 2.5.3
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
